[package]
name = "ezRest"
version = "0.1.0"
authors = ["simon", "gus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
diesel = { version = "1.4.4", features = ["mysql"] }
dotenv = "0.15.0"
